/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CitizenshipRouteImport } from './routes/citizenship'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as SealRouteImport } from './routes/seal'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenshipRoute = CitizenshipRouteImport.update({
  id: '/citizenship',
  path: '/citizenship',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const SealRoute = SealRouteImport.update({
  id: '/seal',
  path: '/seal',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citizenship': typeof CitizenshipRoute
  '/constitution': typeof ConstitutionRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/government': typeof GovernmentRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/protocols': typeof ProtocolsRoute
  '/seal': typeof SealRoute
  '/transactions': typeof TransactionsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citizenship': typeof CitizenshipRoute
  '/constitution': typeof ConstitutionRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/government': typeof GovernmentRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/protocols': typeof ProtocolsRoute
  '/seal': typeof SealRoute
  '/transactions': typeof TransactionsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citizenship': typeof CitizenshipRoute
  '/constitution': typeof ConstitutionRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/docs': typeof DocsRoute
  '/governance': typeof GovernanceRoute
  '/government': typeof GovernmentRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/protocols': typeof ProtocolsRoute
  '/seal': typeof SealRoute
  '/transactions': typeof TransactionsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/citizenship'
    | '/constitution'
    | '/contracts'
    | '/dashboard'
    | '/deploy'
    | '/docs'
    | '/governance'
    | '/government'
    | '/ledger'
    | '/pricing'
    | '/protocols'
    | '/seal'
    | '/transactions'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/citizenship'
    | '/constitution'
    | '/contracts'
    | '/dashboard'
    | '/deploy'
    | '/docs'
    | '/governance'
    | '/government'
    | '/ledger'
    | '/pricing'
    | '/protocols'
    | '/seal'
    | '/transactions'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/citizenship'
    | '/constitution'
    | '/contracts'
    | '/dashboard'
    | '/deploy'
    | '/docs'
    | '/governance'
    | '/government'
    | '/ledger'
    | '/pricing'
    | '/protocols'
    | '/seal'
    | '/transactions'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CitizenshipRoute: typeof CitizenshipRoute
  ConstitutionRoute: typeof ConstitutionRoute
  ContractsRoute: typeof ContractsRoute
  DashboardRoute: typeof DashboardRoute
  DeployRoute: typeof DeployRoute
  DocsRoute: typeof DocsRoute
  GovernanceRoute: typeof GovernanceRoute
  GovernmentRoute: typeof GovernmentRoute
  LedgerRoute: typeof LedgerRoute
  PricingRoute: typeof PricingRoute
  ProtocolsRoute: typeof ProtocolsRoute
  SealRoute: typeof SealRoute
  TransactionsRoute: typeof TransactionsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizenship': {
      id: '/citizenship'
      path: '/citizenship'
      fullPath: '/citizenship'
      preLoaderRoute: typeof CitizenshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seal': {
      id: '/seal'
      path: '/seal'
      fullPath: '/seal'
      preLoaderRoute: typeof SealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CitizenshipRoute: CitizenshipRoute,
  ConstitutionRoute: ConstitutionRoute,
  ContractsRoute: ContractsRoute,
  DashboardRoute: DashboardRoute,
  DeployRoute: DeployRoute,
  DocsRoute: DocsRoute,
  GovernanceRoute: GovernanceRoute,
  GovernmentRoute: GovernmentRoute,
  LedgerRoute: LedgerRoute,
  PricingRoute: PricingRoute,
  ProtocolsRoute: ProtocolsRoute,
  SealRoute: SealRoute,
  TransactionsRoute: TransactionsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
