/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmplifyRouteImport } from './routes/amplify'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CitizenshipRouteImport } from './routes/citizenship'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as SealRouteImport } from './routes/seal'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RReceiptIdRouteImport } from './routes/r.$receiptId'
import { Route as RegistryIndexRouteImport } from './routes/registry.index'
import { Route as RegistrySlugRouteImport } from './routes/registry.$slug'
import { Route as ApiPublicBadgeDigestRouteImport } from './routes/api/public/badge.$digest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmplifyRoute = AmplifyRouteImport.update({
  id: '/amplify',
  path: '/amplify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenshipRoute = CitizenshipRouteImport.update({
  id: '/citizenship',
  path: '/citizenship',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const SealRoute = SealRouteImport.update({
  id: '/seal',
  path: '/seal',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RReceiptIdRoute = RReceiptIdRouteImport.update({
  id: '/r/$receiptId',
  path: '/r/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrySlugRoute = RegistrySlugRouteImport.update({
  id: '/registry/$slug',
  path: '/registry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBadgeDigestRoute = ApiPublicBadgeDigestRouteImport.update({
  id: '/api/public/badge/$digest',
  path: '/api/public/badge/$digest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amplify': typeof AmplifyRoute
  '/auth': typeof AuthRoute
  '/citizenship': typeof CitizenshipRoute
  '/constitution': typeof ConstitutionRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/docs': typeof DocsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/governance': typeof GovernanceRoute
  '/government': typeof GovernmentRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/protocols': typeof ProtocolsRoute
  '/seal': typeof SealRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transactions': typeof TransactionsRoute
  '/verify': typeof VerifyRoute
  '/r/$receiptId': typeof RReceiptIdRoute
  '/registry/$slug': typeof RegistrySlugRoute
  '/registry/': typeof RegistryIndexRoute
  '/api/public/badge/$digest': typeof ApiPublicBadgeDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amplify': typeof AmplifyRoute
  '/auth': typeof AuthRoute
  '/citizenship': typeof CitizenshipRoute
  '/constitution': typeof ConstitutionRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/docs': typeof DocsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/governance': typeof GovernanceRoute
  '/government': typeof GovernmentRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/protocols': typeof ProtocolsRoute
  '/seal': typeof SealRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transactions': typeof TransactionsRoute
  '/verify': typeof VerifyRoute
  '/r/$receiptId': typeof RReceiptIdRoute
  '/registry/$slug': typeof RegistrySlugRoute
  '/registry': typeof RegistryIndexRoute
  '/api/public/badge/$digest': typeof ApiPublicBadgeDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amplify': typeof AmplifyRoute
  '/auth': typeof AuthRoute
  '/citizenship': typeof CitizenshipRoute
  '/constitution': typeof ConstitutionRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/deploy': typeof DeployRoute
  '/docs': typeof DocsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/governance': typeof GovernanceRoute
  '/government': typeof GovernmentRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/protocols': typeof ProtocolsRoute
  '/seal': typeof SealRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transactions': typeof TransactionsRoute
  '/verify': typeof VerifyRoute
  '/r/$receiptId': typeof RReceiptIdRoute
  '/registry/$slug': typeof RegistrySlugRoute
  '/registry/': typeof RegistryIndexRoute
  '/api/public/badge/$digest': typeof ApiPublicBadgeDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amplify'
    | '/auth'
    | '/citizenship'
    | '/constitution'
    | '/contracts'
    | '/dashboard'
    | '/deploy'
    | '/docs'
    | '/feed.xml'
    | '/governance'
    | '/government'
    | '/ledger'
    | '/pricing'
    | '/protocols'
    | '/seal'
    | '/sitemap.xml'
    | '/transactions'
    | '/verify'
    | '/r/$receiptId'
    | '/registry/$slug'
    | '/registry/'
    | '/api/public/badge/$digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amplify'
    | '/auth'
    | '/citizenship'
    | '/constitution'
    | '/contracts'
    | '/dashboard'
    | '/deploy'
    | '/docs'
    | '/feed.xml'
    | '/governance'
    | '/government'
    | '/ledger'
    | '/pricing'
    | '/protocols'
    | '/seal'
    | '/sitemap.xml'
    | '/transactions'
    | '/verify'
    | '/r/$receiptId'
    | '/registry/$slug'
    | '/registry'
    | '/api/public/badge/$digest'
  id:
    | '__root__'
    | '/'
    | '/amplify'
    | '/auth'
    | '/citizenship'
    | '/constitution'
    | '/contracts'
    | '/dashboard'
    | '/deploy'
    | '/docs'
    | '/feed.xml'
    | '/governance'
    | '/government'
    | '/ledger'
    | '/pricing'
    | '/protocols'
    | '/seal'
    | '/sitemap.xml'
    | '/transactions'
    | '/verify'
    | '/r/$receiptId'
    | '/registry/$slug'
    | '/registry/'
    | '/api/public/badge/$digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmplifyRoute: typeof AmplifyRoute
  AuthRoute: typeof AuthRoute
  CitizenshipRoute: typeof CitizenshipRoute
  ConstitutionRoute: typeof ConstitutionRoute
  ContractsRoute: typeof ContractsRoute
  DashboardRoute: typeof DashboardRoute
  DeployRoute: typeof DeployRoute
  DocsRoute: typeof DocsRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  GovernanceRoute: typeof GovernanceRoute
  GovernmentRoute: typeof GovernmentRoute
  LedgerRoute: typeof LedgerRoute
  PricingRoute: typeof PricingRoute
  ProtocolsRoute: typeof ProtocolsRoute
  SealRoute: typeof SealRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransactionsRoute: typeof TransactionsRoute
  VerifyRoute: typeof VerifyRoute
  RReceiptIdRoute: typeof RReceiptIdRoute
  RegistrySlugRoute: typeof RegistrySlugRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  ApiPublicBadgeDigestRoute: typeof ApiPublicBadgeDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amplify': {
      id: '/amplify'
      path: '/amplify'
      fullPath: '/amplify'
      preLoaderRoute: typeof AmplifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizenship': {
      id: '/citizenship'
      path: '/citizenship'
      fullPath: '/citizenship'
      preLoaderRoute: typeof CitizenshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seal': {
      id: '/seal'
      path: '/seal'
      fullPath: '/seal'
      preLoaderRoute: typeof SealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$receiptId': {
      id: '/r/$receiptId'
      path: '/r/$receiptId'
      fullPath: '/r/$receiptId'
      preLoaderRoute: typeof RReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$slug': {
      id: '/registry/$slug'
      path: '/registry/$slug'
      fullPath: '/registry/$slug'
      preLoaderRoute: typeof RegistrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/badge/$digest': {
      id: '/api/public/badge/$digest'
      path: '/api/public/badge/$digest'
      fullPath: '/api/public/badge/$digest'
      preLoaderRoute: typeof ApiPublicBadgeDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmplifyRoute: AmplifyRoute,
  AuthRoute: AuthRoute,
  CitizenshipRoute: CitizenshipRoute,
  ConstitutionRoute: ConstitutionRoute,
  ContractsRoute: ContractsRoute,
  DashboardRoute: DashboardRoute,
  DeployRoute: DeployRoute,
  DocsRoute: DocsRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  GovernanceRoute: GovernanceRoute,
  GovernmentRoute: GovernmentRoute,
  LedgerRoute: LedgerRoute,
  PricingRoute: PricingRoute,
  ProtocolsRoute: ProtocolsRoute,
  SealRoute: SealRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransactionsRoute: TransactionsRoute,
  VerifyRoute: VerifyRoute,
  RReceiptIdRoute: RReceiptIdRoute,
  RegistrySlugRoute: RegistrySlugRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  ApiPublicBadgeDigestRoute: ApiPublicBadgeDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
